name: MarioWorld
main: littlegruz.marioworld.MarioMain
author: LittleGruz
website: http://www.littlegruz.com
version: 4.6
commands:
   mariorestart:
      description: Resets all the Mario item blocks and player stats to their original state
      usage: /mariorestart [c] [world_name]
   mariodamage:
      description: Toggles damage between being similar to Mario and not similar
      usage: /mariodamage
   addmarioworld:
      description: Adds the current world to the list of worlds effected by the mod
      usage: /addmarioworld
   removemarioworld:
      description: Removes the current world from the list of worlds effected by the mod
      usage: /removemarioworld
   clearmariocheckpoint:
      description: Resets the checkpoint of a player back to the default spawn
      usage: /clearmariocheckpoint
   changelanguage:
      description: Changes the language of displayed messages
      usage: /changelanguage
   marioscore:
      description: Displays a player's score
      usage: /marioscore <player_name>
   displaywarppipes:
      description: Lists the locations of the warp pipe pairs
      usage: /displaywarppipes
   cancelwarppipe:
      description: Cancels the current placement of a warp pipe
      usage: /cancelwarppipe
   keepmariocoins:
      description: Toggles whether or not coins are kept on a "game over" or life gain
      usage: /keepmariocoins
   changedefaultlives:
      description: Changes the the number of lives a player gets when starting/after game over
      usage: /changedefaultlives <amount>
   changecoinlevelup:
      description: Changes the the number of coins a player needs to level up
      usage: /changecoinlevelup <amount>
   mario:
      description: Adds or subtracts lives/coins from a player
      usage: /mario <attribute> <add/sub> <player_name> <amount>
   cpreturn:
      description: Returns player to their checkpoint
      usage: /cpreturn <player_name>
permissions:
   marioworld.admincommands:
      description: Any of the administration commands
      default: op
softdepend: [Spout, Multiverse-Core, My Worlds, MultiWorld]