name: MarioWorld
main: littlegruz.marioworld.MarioMain
version: 4.0
commands:
   mariorestart:
      description: Resets all the Mario item blocks and player stats to their original state
      usage: /mariorestart
   mariodamage:
      description: Toggles the damage to and from being similar to in the Mario games
      usage: /mariodamage
   addmarioworld:
      description: Adds the current world to the list of worlds effected by the mod
      usage: /addmarioworld
   removemarioworld:
      description: Removes the current world from the list of worlds effected by the mod
      usage: /removemarioworld
   clearmariocheckpoint:
      description: Resets the checkpoint of a player back to the default spawn
      usage: /clearmariocheckpoint
   changelanguage:
      description: Changes the language of displayed messages
      usage: /changelanguage
   marioscore:
      description: Displays a player's score
      usage: /marioscore <player_name>
permissions:
   marioworld.admincommands:
      description: Any of the administration commands
      default: op
softdepend: [Spout]